algoritmo "Algoritmo de funções_predefinidas no sistema"
//Funções já predefinidas no sistemas do visualg
var
N:caractere
inicio
escreval("Digite seu nome: ")
leia(N)
escreval("Seu nome possui um total de:", compr(N), " letras")
escreval("Seu nome em letras maiúsculas: ", maiusc(N))
escreval("Seu nome em letras minúsculas: ", minusc(N))
escreval("A primeira letra do seu nome é: ", copia(N,1,1))
//Exemplos de funções

fimalgoritmo